### ISSUE TITLE
Error on Gnome 3.38.1

### ISSUE THREAD

**Issue by oyvindskaaden** [jeffchannell/jiggle#25]
When using Gnome version 3.38.1 i get the error `No JS module 'tweener' found in search path`. Probably some removed files. 

I see this is reported on gnome extensions website as well.

**Comment by jeffchannell** [comment]
Thanks for the report.

I’ll take a look and see what I can find. It sounds like the Gnome devs moved something?

**Comment by jeffchannell** [comment]
It looks as though `imports.ui.tweener` has been moved to `imports.tweener.tweener`. I'll abstract out the import a bit and get this fixed up...

**Comment by jeffchannell** [comment]
I've started a branch here:

https://github.com/jeffchannell/jiggle/tree/issue25

This patch doesn't fail on an existing stable install, and as soon as I can get Gnome 3.38.1 running in a VM and confirm it's working, I'll merge it. In the meantime, if you want to test you can clone this repo, `git checkout issue25`, then `make local`. This installs the development version. Edit your extension settings and switch from stable to dev and restart Gnome (log out/in or alt+f2 and `r`).

**Comment by jeffchannell** [comment]
I've merged a patch that seems to fix this issue. I am going to tackle one more bug before submitting a new release, but you can use the latest `master` to patch your local install (and if you need help, just ask).

**Comment by oyvindskaaden** [comment]
Amazing! Thanks for the great extention btw😁

**Comment by jeffchannell** [comment]
https://extensions.gnome.org/review/21242
Fix is awaiting review

**Comment by jeffchannell** [comment]
Review is complete and the new release is available.
