### ISSUE TITLE
Please Fix to Gnome 3.38.1

### ISSUE THREAD

**Issue by andrewdomingues** [jeffchannell/jiggle#27]
This is a Great extension, Please fix it.

**Comment by jeffchannell** [comment]
Is this a duplicate of #25 ? Can you check logs for the same error? Thanks!

**Comment by jeffchannell** [comment]
Closing as a duplicate of #25 - this seems like a straightforward patch, so expect a fix posted here soon.

**Comment by jeffchannell** [comment]
New release is now available
