### ISSUE TITLE
does not work with trackpad

### ISSUE THREAD

**Issue by tronta** [jeffchannell/jiggle#42]
for me it works only with the mouse and not with the trackpad.
With the trackpad, simply nothing happens. Not sure if is intended, but it would be great if it would work also with the trackpad.

I'm using the latest Fedora 34.

**Comment by tronta** [comment]
Funnily works now... but I'm pretty sure it used not to work before...

**Comment by vchernin** [comment]
Trackpad works fine for me also on fedora 34. This issue should be closed unless anyone is experiencing this issue.

**Comment by tronta** [comment]
Works now for me. Not sure what has changed.
