### ISSUE TITLE
Gnome 41 support

### ISSUE THREAD

**Issue by rootd** [jeffchannell/jiggle#50]
Currently the extension is marked as incompatible on Gnome 41. It would be nice to have that supported.

**Comment by rohmishra** [comment]
I dont think anything related to this extension has changed in shell since disabling compatibility check allows the extension to work on 41. Should just need updated manifest.

**Comment by rootd** [comment]
First of all, thanks a lot for the update for Gnome 41!

The extension itself works, however I'm unable of opening the extension settings. It simply doesn't open.
Let me know if there's any more information I can provide

**Comment by rohmishra** [comment]
Hmm, that is a bit weird, it seems to be working just fine for me on 41.1.
![image](https://user-images.githubusercontent.com/2221064/144759366-2f106633-decd-4382-b87f-08845b496150.png)

To start, can you run  `journalctl -f` and then try to launch the settings panel? Share any warnings or errors that it may produce when you click on the cog-wheel against the extension. Also can you share a SS of Settings > About? @rootd

**Comment by laurinneff** [comment]
Hey, you should reupload it on EGO, otherwise it won't be possible to run the extension on GNOME 41 unless you install it manually

**Comment by jeffchannell** [comment]
https://extensions.gnome.org/review/32717
